apiVersion: v1
kind: ReplicationController
metadata:
  name: my-galaxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: galaxy
    spec:
      containers:
      - name: galaxy
        image: bgruening/galaxy-stable:dev
        ports:
        - containerPort: 80
